TourKProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from homeApp.views import home
from django.conf import settings
from django.conf.urls.static import static
import xadmin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('destinationApp/', include('destinationApp.urls')),
    path('ticketApp/', include('ticketApp.urls')),
    path('hotelApp/', include('hotelApp.urls')),
    path('search/', include('haystack.urls')),
    path('noteApp/', include('noteApp.urls')),
    path('communtityApp/', include('communityApp.urls')),
    path('messageApp/', include('messageApp.urls')),
    path('', home, name='home'),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('xadmin/', xadmin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

communityApp/urls.py
from django.urls import path
from . import views

app_name = 'communityApp'

urlpatterns = [
    path('strategy/', views.strategy, name='strategy'),
    path('quiz/', views.quiz, name='quiz'),
    path('reply/<int:id>/', views.reply, name='reply'),
    path('visa/', views.visa, name='visa'),
    path('visaData/<int:id>/', views.visaData, name='visaData'),
    path('getDoc/<int:id>/', views.getDoc, name='getDoc'),
    path('search/', views.search, name='search'),
    # path('quizdelete/<int:id>', views.quizdelete, name='quizdelete')
    # path('replydelete/<int:id>/<int:id>/', views.replydelete, name='replydelete')
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

messageApp/urls.py
from django.urls import path
from .import views


app_name = 'messageApp'

urlpatterns = [
    path('message/', views.message, name='message'),# 欢迎留言
    path('showreply/', views.showreply, name='showreply'),# 留言回复
    path('about/', views.about, name='about'),
    path('getDoc/<int:id>/', views.getDoc, name='getDoc'),
]

noteApp/urls.py
from django.urls import path
from . import views

app_name = 'noteApp'

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('route', views.routes, name='routes'),
    path('noteDetail/<int:id>/', views.noteDetail, name='noteDetail'),

]

communityApp/models.py
from django.db import models
from django.utils import timezone

class Quiz(models.Model):
    name = models.CharField(max_length=10, verbose_name='姓名')
    title = models.CharField(max_length=40, verbose_name='留言标题')
    content = models.TextField(verbose_name='留言内容')
    quizDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='提交时间')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '问答'
        verbose_name_plural = '问答'
        ordering = ('-quizDate', )

class Reply(models.Model):
    replyname = models.CharField(max_length=20, verbose_name='姓名')
    title = models.ForeignKey(Quiz, related_name='replys', verbose_name='回复', on_delete=models.CASCADE, null=True)
    replycontent = models.TextField(verbose_name='回复')
    replyDate = models.DateTimeField(max_length=20, default=timezone.now, verbose_name='回复时间')

    class Meta:
        verbose_name = '问题回复'
        verbose_name_plural = '问题回复'

class Visa(models.Model):
    title = models.CharField(max_length=100, verbose_name='签证名称')
    city = models.CharField(max_length=20, verbose_name='城市')
    type = models.CharField(max_length=20, verbose_name='签证类型')
    expire = models.CharField(max_length=20, verbose_name='有效期')
    staydays = models.CharField(max_length=20, verbose_name='停留天数')
    number = models.CharField(max_length=20, verbose_name='入境次数')
    order = models.CharField(max_length=20, verbose_name='订单有效期')
    place = models.CharField(max_length=100, verbose_name='受理地区')
    price = models.IntegerField(verbose_name='价格')
    discount = models.CharField(max_length=100, verbose_name='优惠信息')
    discountprice = models.IntegerField(verbose_name='优惠价格')
    orderknow = models.CharField(max_length=100, verbose_name='预订须知')
    slogan = models.ImageField(upload_to='Visa/',
                              blank=True,
                              verbose_name='封面图片')
    flow = models.ImageField(upload_to='Visa/',
                              blank=True,
                              verbose_name='办签流程')
    description = models.TextField(max_length=500,
                                   blank=True,
                                   null=True,
                                   verbose_name='取消政策')
    tip = models.TextField(max_length=500,
                                   blank=True,
                                   null=True,
                                   verbose_name='温馨提示')
    tips = models.TextField(max_length=500,
                                   blank=True,
                                   null=True,
                                   verbose_name='重要提示')
    message = models.TextField(max_length=500,
                                   blank=True,
                                   null=True,
                                   verbose_name='产品服务信息')
    views = models.PositiveIntegerField('浏览量', default=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '签证'
        verbose_name_plural = '签证'

class visaAbout(models.Model):
    title = models.ForeignKey(Visa, related_name='abouts', verbose_name='签证名称', on_delete=models.CASCADE, null=True)
    about = models.ImageField(upload_to='Visa/',
                              blank=True,
                              verbose_name='产品介绍')
    class Meta:
        verbose_name = '产品介绍'
        verbose_name_plural = '产品介绍'

class visaData(models.Model):
    PEOPLE_CHOICES = (
        ('在职人员', '在职人员'), ('自由职业', '自由职业'), ('在校学生', '在校学生'),
        ('退休人员', '退休人员'), ('学龄前儿童', '学龄前儿童'),
    )
    title = models.ForeignKey(Visa, related_name='datas', verbose_name='签证名称', on_delete=models.CASCADE, null=True)
    people = models.CharField(choices=PEOPLE_CHOICES, max_length=10, verbose_name='人员类型')
    data = models.CharField(max_length=10, verbose_name='材料名称')
    type = models.CharField(max_length=10, verbose_name='材料类型')
    amount = models.IntegerField(verbose_name='材料数量')
    description = models.TextField(max_length=500,
                                   blank=True,
                                   null=True,
                                   verbose_name='材料说明')
    class Meta:
        verbose_name = '所需材料'
        verbose_name_plural = '所需材料'


class Strategy(models.Model):
    title = models.CharField(max_length=20, verbose_name='攻略名称')
    file = models.FileField(upload_to='Strategy/', blank=True, verbose_name='攻略资料')
    description = models.TextField(max_length=500,
                                   blank=True,
                                   null=True,
                                   verbose_name='攻略描述')
    photo = models.ImageField(upload_to='Strategy/Img/',
                              blank=True,
                              verbose_name='封面图片')
    publishDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='发布时间')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '攻略'
        verbose_name_plural = verbose_name
        ordering = ['-publishDate']

communityApp/forms.py
from django import forms
from .models import Quiz, Reply

class QuizForm(forms.ModelForm):  #建立模型表单类
    class Meta:   #通过元信息类进行模型的定制化
        model = Quiz  #需要定制化的模型
        fields = ('name', 'title', 'content')  #需要定制化的字段

class ReplyForm(forms.ModelForm):  #建立模型表单类
    class Meta:   #通过元信息类进行模型的定制化
        model = Reply  #需要定制化的模型
        fields = ('replyname', 'title', 'replycontent')  #需要定制化的字段

communityApp/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from .models import Quiz, Visa, Strategy
from django.shortcuts import get_object_or_404
from .forms import QuizForm, ReplyForm
from django.core.paginator import Paginator
from pyquery import PyQuery as pq
from django.http import StreamingHttpResponse, JsonResponse

import os

def strategy(request):
    strategyList = Strategy.objects.all().order_by('-publishDate')

    for doc in strategyList:
        html = pq(doc.title)
        doc.mytxt = pq(html)('p').text()

    p = Paginator(strategyList, 6)
    if p.num_pages <= 1:
        pageDate = ''
    else:
        page = int(request.GET.get('page', 1))
        strategyList = p.page(page)
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        total_pages = p.num_pages
        page_range = p.page_range
        if page == 1:
            right = page_range[page:page + 2]
            print(total_pages)
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page == total_pages:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            right = page_range[page:page + 2]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        pageDate = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'total_pages': total_pages,
            'page': page,
        }

    return render(
        request, 'strategyList.html', {
            'active_menu': 'community',
            'sub_menu': 'strategys',
            'strategyList': strategyList,
            'pageDate': pageDate,
        }
    )

def read_file(file_name, size):
    with open(file_name, mode='rb') as fp:
        while True:
            c = fp.read(size)
            if c:
                yield c
            else:
                break

def getDoc(request, id):
    doc = get_object_or_404(Strategy, id=id)
    update_to, filename = str(doc.file).split('/')
    filepath = '%s/media/%s/%s' % (os.getcwd(), update_to, filename)
    response = StreamingHttpResponse(read_file(filepath, 512))
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="{}"'.format(filename)
    return response

def quiz(request):
    if request.method == 'POST':
        quizForm = QuizForm(data=request.POST) #创建模型表单对象
        if quizForm.is_valid():
            quizForm.save() #存到数据库
            return render(request, 'successq.html')
    else:  #没有提交
            quizForm = QuizForm()  #创建模型表单对象，并传给message.html

    submenu = 'quizs'
    quizList = Quiz.objects.all()

    p = Paginator(quizList, 5)
    if p.num_pages <= 1:
        pageDate = ''
    else:
        page = int(request.GET.get('page', 1))
        quizList = p.page(page)
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        total_pages = p.num_pages
        page_range = p.page_range
        if page == 1:
            right = page_range[page:page+2]
            print(total_pages)
            if right[-1] < total_pages-1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page == total_pages:
            left = page_range[(page-3) if (page-3) > 0 else 0:page-1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page-3) if (page-3) > 0 else 0:page-1]
            right = page_range[page:page+2]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
            if right[-1] < total_pages-1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        pageDate = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'total_pages': total_pages,
            'page': page,
        }

    return render(request, 'quiz.html', {
        'active_menu': 'community',
        'sub_menu': submenu,
        'quizList': quizList,
        'quizForm': quizForm,
        'pageDate': pageDate,
    })

def reply(request, id):

    if request.method == 'POST':
        replyForm = ReplyForm(data=request.POST) #创建模型表单对象
        if replyForm.is_valid():
            replyForm.save() #存到数据库
            return render(request, 'successr.html')
    else:  #没有提交
            replyForm = ReplyForm()  #创建模型表单对象，并传给message.html

    replyList = get_object_or_404(Quiz, id=id)

    return render(request, 'reply.html', {
        'active_menu': 'community',
        'replyList': replyList,
        'replyForm': replyForm,
    })

def visa(request):
    visaList = Visa.objects.all().order_by('-views')

    return render(request, 'visaList.html', {
        'active_menu': 'community',
        'visaList': visaList,
        'sub_menu': 'visas',
    })

def visaData(request, id):
    visadetail = get_object_or_404(Visa, id=id)
    PeopleList = visadetail.datas.all()
    peopleList = PeopleList.values('people').distinct().order_by('people')
    List = {}
    for pe in peopleList:
        peo = pe['people']
        pdList = PeopleList.filter(people=peo)
        List[peo] = pdList

    return render(
        request, 'visaDetail.html', {
            'active_menu': 'community',
            'sub_menu': 'visas',
            'visadetail': visadetail,
            'List': List,
            'peopleList': peopleList,
        }
    )

def search(request):

    if request.method == 'POST':
        quizForm = QuizForm(data=request.POST) #创建模型表单对象
        if quizForm.is_valid():
            quizForm.save() #存到数据库
            return render(request, 'successq.html')
    else:  #没有提交
            quizForm = QuizForm()  #创建模型表单对象，并传给message.html

    keyword = request.GET.get('keyword')
    quizList = Quiz.objects.filter(title__icontains=keyword)
    quizName = "关于" + "\"" + keyword + "\"" + "的搜索结果"

    return render(request, 'searchquiz.html', {
        'active_menu': 'community',
        'sub_menu': 'quizs',
        'quizName': quizName,
        'quizList': quizList,
        'quizForm': quizForm,
    })

communityApp/templates/quiz.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}
问答
{% endblock %}
{% block content %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
<!--广告横幅-->
    <div class="container-fluid">
        <div class="row">
            <img class="img-responsive model-img" style="width: 100%;height: 470px" src="{% static 'img/ticket/4.jpeg' %}">
        </div>
    </div>
    <!--主体内容-->
    <div class="container">
        <div class="row row-3" style="margin-top: 5px">
            <!--侧边导航栏-->
            <div class="col-md-3">
                <div class="model-title">
                    社区
                </div>
                <div class="model-list">
                    <ul class="list-group">
                        <li class="list-group-item" id="strategys">
                            <a href="{% url 'communityApp:strategy' %}">攻略下载</a>
                        </li>
                        <li class="list-group-item" id="quizs">
                            <a href="{% url 'communityApp:quiz' %}">问答</a>
                        </li>
                        <li class="list-group-item" id="visas">
                            <a href="{% url 'communityApp:visa' %}">签证</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!--说明文字与图片-->
            <div class="col-md-9">
                <div class="model-details-title">
                    问答Q&A
                    <div class="col-md-7 hidden-xs model-details-title-search" style="float: right;width: 300px">
                        <form method="get" id="searchform" action="{% url 'communityApp:search' %}">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" name="keyword" class="form-control" placeholder="请输入关键词" required />
                                <span class="input-group-btn">
                                    <input type="submit" class="btn btn-default" value="查询" />
                                </span>
                            </div>
                        </form>
                    </div>
                    <a style="font-size: 13px" href="#ask">我要提问</a>
                </div>
                  <!--此处填入产品列表内容-->
                <div class="model-details">
                    {% for qz in quizList %}
                        <div class="col-md-12">
                            <h4>
                                <img src="{% static 'img/community/newsicon.gif' %}" style="width: 35px">
                                <a href="{% url 'communityApp:reply' qz.id %}"
                                   style="color: black">{{ qz.title }}</a>
                            </h4>
                            <p style="color:#777777;">
                                {{ qz.content|truncatechars:"150" }}
                            </p>
                            <p style="font-size: 10px;color: grey;float: right">
                                <i style="font-size: 12px;color: #F4A460;font-style: normal;font-weight: bolder">
                                    {{ qz.name }}</i>
                                &nbsp;&nbsp;&nbsp;发布于{{ qz.quizDate }}
                            </p>
                        </div>
                    {% endfor %}
                    {% if pageDate %}
                    <div class="paging">
                        <ul id="pages" class="pagination">
                            {% if pageDate.first %}
                                <li><a href="?page=1"></a></li>
                            {% endif %}
                            {% if pageDate.left %}
                                {% if pageDate.left_has_more %}
                                    <li><span>...</span></li>
                                {% endif %}
                                {% for i in pageDate.left %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endfor %}
                            {% endif %}
                            <li class="active"><a href="?page={{ pageDate.page }}">{{ pageDate.page }}</a></li>
                            {% if pageDate.right %}
                                {% for i in pageDate.right %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endfor %}
                                {% if pageDate.right_has_more %}
                                    <li><span>...</span></li>
                                {% endif %}
                            {% endif %}
                            {% if pageDate.last %}
                                <li><a href="?page={{ pageDate.total_pages }}">{{ pageDate.total_pages }}</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="model-details-title">
            <a name="ask" style="color: #F4A460">我要提问</a>
        </div>
        <div class="col-md-12">
            <div class="panel-body">
                <div class="row">
                    <form action="." name="quizForm" method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
                        {% csrf_token %}  <!--规避跨站请求，不加，后台无法接受数据-->
                        <!-- 左侧 -->
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">昵称：</label>
                                <div class="col-sm-10">
                                    {{quizForm.name|add_class:"form-control"|attr:"placeholder=请填写昵称"}}<!--模板表单变量-->
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">提问：</label>
                                <div class="col-sm-10">
                                    {{quizForm.title|add_class:"form-control"}}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label">具体内容：</label>
                                <div class="col-md-10">
                                    {{quizForm.content|add_class:"form-control"}}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <center><input type="submit" class="btn btn-primary" value="提交" /></center>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

communityApp/templates/searchquiz.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}
问答
{% endblock %}
{% block content %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
<!--广告横幅-->
    <div class="container-fluid">
        <div class="row">
            <img class="img-responsive model-img" style="width: 100%;" src="{% static 'img/destination/special/spots1.jpg' %}">
        </div>
    </div>
    <!--主体内容-->
    <div class="container">
        <div class="row row-3">
            <!--侧边导航栏-->
            <div class="col-md-3">
                <div class="model-title">
                    社区
                </div>
                <div class="model-list">
                    <ul class="list-group">
                        <li class="list-group-item" id="strategys">
                            <a href="{% url 'communityApp:strategy' %}">攻略下载</a>
                        </li>
                        <li class="list-group-item" id="quizs">
                            <a href="{% url 'communityApp:quiz' %}">问答</a>
                        </li>
                        <li class="list-group-item" id="visas">
                            <a href="{% url 'communityApp:visa' %}">签证</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!--说明文字与图片-->
            <div class="col-md-9">
                <div class="model-details-title">
                    {{ quizName }}
                    <div class="col-md-7 hidden-xs model-details-title-search" style="float: right;width: 300px">
                        <form method="get" id="searchform" action="{% url 'communityApp:search' %}">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" name="keyword" class="form-control" placeholder="请输入关键词" required />
                                <span class="input-group-btn">
                                    <input type="submit" class="btn btn-default" value="查询" />
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
                  <!--此处填入产品列表内容-->
                <div class="model-details">
                    {% for qz in quizList %}
                        <div class="col-md-12">
                            <h4>
                                <img src="{% static 'img/community/newsicon.gif' %}" style="width: 35px">
                                <a href="{% url 'communityApp:reply' qz.id %}"
                                   style="color: black">{{ qz.title }}</a>
                            </h4>
                            <p style="color:#777777;">
                                {{ qz.content|truncatechars:"150" }}
                            </p>
                            <p style="font-size: 10px;color: grey;float: right">
                                <i style="font-size: 12px;color: #F4A460;font-style: normal;font-weight: bolder">
                                    {{ qz.name }}</i>
                                &nbsp;&nbsp;&nbsp;发布于{{ qz.quizDate }}
                            </p>
                        </div>
                    {% empty %}
                        <h4 align="center" style="color: #777777;padding-top: 30px">
                            米安内！没有找到相关问答！请输入别的关键字哦~<br><br>
                            或者您可以向别的悠崽<a href="#ask" style="color:#F4A460;">提问</a>哦&nbsp;⬇
                        </h4>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="model-details-title">
            <a name="ask" style="color: #F4A460">我要提问</a>
        </div>
        <div class="col-md-12">
            <div class="panel-body">
                <div class="row">
                    <form action="." name="quizForm" method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
                        {% csrf_token %}  <!--规避跨站请求，不加，后台无法接受数据-->
                        <!-- 左侧 -->
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">昵称：</label>
                                <div class="col-sm-10">
                                    {{quizForm.name|add_class:"form-control"|attr:"placeholder=请填写昵称"}}<!--模板表单变量-->
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">提问：</label>
                                <div class="col-sm-10">
                                    {{quizForm.title|add_class:"form-control"}}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label">具体内容：</label>
                                <div class="col-md-10">
                                    {{quizForm.content|add_class:"form-control"}}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <center><input type="submit" class="btn btn-primary" value="提交" /></center>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

communityApp/templates/strategyList.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}攻略下载{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-3">
                <div class="model-title">
                    社区
                </div>
                <div class="model-list">
                    <ul class="list-group">
                        <li class="list-group-item" id="strategys">
                            <a href="{% url 'communityApp:strategy' %}">攻略下载</a>
                        </li>
                        <li class="list-group-item" id="quizs">
                            <a href="{% url 'communityApp:quiz' %}">问答</a>
                        </li>
                        <li class="list-group-item" id="visas">
                            <a href="{% url 'communityApp:visa' %}">签证</a>
                        </li>
                    </ul>
                </div>
            </div>
        <div class="model-details-title col-md-9">
            攻略
        </div>
        <div class="row col-md-9">
            {% for st in strategyList %}
                <div class="col-md-4" style="margin-bottom: 5px;height: 385px">
                    <div class="thumbnail">
                        <a href="{% url 'communityApp:getDoc' st.id %}">
                            <img src="{{ st.photo.url }}" style="width: 100%">
                        </a>
                        <div class="caption">
                            <p style="margin-bottom: 0">
                                <a href="{% url 'communityApp:getDoc' st.id %}"><b>{{ st.title }}</b></a>
                                <ol class="dropdown" style="float: right">
                                    <a class="dropdown-toggle">⏷</a>
                                    <i class="dropdown-menu" style="font-size: 10px;padding: 5px;font-style: normal">{{ st.description }}</i>
                                </ol>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-md-12">
            <div class="col-md-3"></div>
            <div class="col-md-9">
                {% if pageDate %}
                    <div class="paging" align="center">
                        <ul id="pages" class="pagination">
                            {% if pageDate.first %}
                                <li><a href="?page=1"></a></li>
                            {% endif %}
                            {% if pageDate.left %}
                                {% if pageDate.left_has_more %}
                                    <li><span>...</span></li>
                                {% endif %}
                                {% for i in pageDate.left %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endfor %}
                            {% endif %}
                            <li class="active"><a href="?page={{ pageDate.page }}">{{ pageDate.page }}</a></li>
                            {% if pageDate.right %}
                                {% for i in pageDate.right %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endfor %}
                                {% if pageDate.right_has_more %}
                                    <li><span>...</span></li>
                                {% endif %}
                            {% endif %}
                            {% if pageDate.last %}
                                <li><a href="?page={{ pageDate.total_pages }}">{{ pageDate.total_pages }}</a></li>
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}