TourKProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from homeApp.views import home
from django.conf import settings
from django.conf.urls.static import static
import xadmin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('destinationApp/', include('destinationApp.urls')),
    path('ticketApp/', include('ticketApp.urls')),
    path('hotelApp/', include('hotelApp.urls')),
    path('search/', include('haystack.urls')),
    path('noteApp/', include('noteApp.urls')),
    path('communtityApp/', include('communityApp.urls')),
    path('messageApp/', include('messageApp.urls')),
    path('', home, name='home'),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('xadmin/', xadmin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

messageApp/urls.py
from django.urls import path
from .import views


app_name = 'messageApp'

urlpatterns = [
    path('message/', views.message, name='message'),# 欢迎留言
    path('showreply/', views.showreply, name='showreply'),# 留言回复
    path('about/', views.about, name='about'),
    path('getDoc/<int:id>/', views.getDoc, name='getDoc'),
]

noteApp/urls.py
from django.urls import path
from . import views

app_name = 'noteApp'

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('route', views.routes, name='routes'),
    path('noteDetail/<int:id>/', views.noteDetail, name='noteDetail'),

]

messageApp/models.py
from django.db import models
from django.utils import timezone

class Message(models.Model):
    name = models.CharField(max_length=20, verbose_name='昵称')
    phone = models.CharField(max_length=20, verbose_name='电话号码')
    email = models.EmailField(max_length=30, verbose_name='邮箱')
    title = models.CharField(max_length=40, verbose_name='留言标题')
    content = models.CharField(max_length=200, verbose_name='留言内容')
    publishDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='提交时间')
    replycontent = models.TextField(blank=True, null=True, verbose_name='回复')
    replyDate = models.DateTimeField(max_length=20, default=timezone.now, verbose_name='回复时间')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '留言'
        verbose_name_plural = verbose_name
        ordering = ['-replyDate']

class Protocol(models.Model):
    title = models.CharField(max_length=20, verbose_name='名称')
    name = models.CharField(max_length=20, blank=True, null=True, verbose_name='简称')
    content = models.TextField(verbose_name='内容')
    file = models.FileField(upload_to='Protocol/', blank=True, verbose_name='协议资料')
    publishDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='提交时间')
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '协议'
        verbose_name_plural = verbose_name
        ordering = ['-publishDate']

messageApp/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):  #建立模型表单类
    class Meta:   #通过元信息类进行模型的定制化
        model = Message  #需要定制化的模型
        fields = ('name', 'phone', 'email', 'title', 'content')  #需要定制化的字段

messageApp/views.py
from django.shortcuts import render
from .forms import MessageForm
from .models import Message, Protocol
from django.shortcuts import get_object_or_404
from django.http import StreamingHttpResponse, JsonResponse
import os

def message(request):
    if request.method == 'POST':
        messageForm = MessageForm(data=request.POST) #创建模型表单对象
        if messageForm.is_valid():
            messageForm.save() #存到数据库
            return render(request, 'successm.html')
    else:  #没有提交
        messageForm = MessageForm()  #创建模型表单对象，并传给message.html
    return render(
        request, 'message.html', {
            'messageForm': messageForm,
        })

def showreply(request):
    replyList = Message.objects.filter(replycontent__isnull=False)  # 得到 有回复 的记录
    return render(request, 'showreply.html', {
        'replyList': replyList
    })

def about(request):
    protocolList = Protocol.objects.all().order_by('publishDate')
    return render(request, 'about.html', {
        'protocolList': protocolList,
    })

def read_file(file_name, size):
    with open(file_name, mode='rb') as fp:
        while True:
            c = fp.read(size)
            if c:
                yield c
            else:
                break

def getDoc(request, id):
    doc = get_object_or_404(Protocol, id=id)
    update_to, filename = str(doc.file).split('/')
    filepath = '%s/media/%s/%s' % (os.getcwd(), update_to, filename)
    response = StreamingHttpResponse(read_file(filepath, 512))
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="{}"'.format(filename)
    return response

messageApp/templates/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
关于悠哉
{% endblock %}

{% block content %}
<!-- 广告横幅 -->
<div class="container-fluid">
    <div class="row">
{#        <img class="img-responsive model-img" src="{% static 'img/about.jpg' %}">#}
    </div>
</div>
<!-- 主体内容 -->
<div class="container">
    <div class="row row-3">
        <div class="col-md-12">
            <div class="model-details-title">
                <h3>
                    <img src="{% static 'img/destination/orang.png' %}" style="width: 10px">
                    <a style="color: black">关于悠哉</a>
                </h3>
            </div>
            <div class="col-md-12">
                <ul class="nav navbar-nav" style="width: 80%;height: 40px;margin-top: 0">
                    <li class="nav-top">
                        <a href="#about" style="font-size: 15px;color: #F4A460">悠哉简介</a>
                    </li>
                    {% for pro in protocolList %}
                    <li class="nav-top">
                        <a href="#{{ pro.name }}" style="font-size: 15px;color: #F4A460">{{ pro.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="model-details">
                <div class="row">
                    <a name="about">
                        <img class="img-responsive" src="{% static 'img/home/logo1.png' %}"
                         style="width: 90%">
                    </a>
                </div>
                <p style="padding-bottom: 15px">
                    悠哉，是新生起的针对韩国旅游的旅游网站。
                    得益于“内容 + 交易” 的核心优势，悠哉更理解哈韩一族的偏好，让复杂的旅游决策、预订和体验，变得简单、高效和便捷。
                    悠哉是旅游社交网站，是数据驱动平台，是新型旅游电商。
                    悠哉基于作者数以计日、呕心沥血的创作，悠哉为用户提供了与众不同的旅游体验。
                    悠哉独有的“内容获客”模式，高效匹配供需， 助力平台商家提升利润率，并重塑旅游产业链。
                    经大量旅行者自主分享，悠哉社区的信息内容不断丰富和完善， 成为年轻一代去往韩国旅游之前首选的“旅游神器”。
                    与父辈们常用的传统在线旅游网站(OTA)相比，悠哉更潮、更酷，深谙“年轻一代的选择”， 帮助他们从不同角度，重新发现世界。
                </p>
            </div>
        </div>
        {% for pro in protocolList %}
            <div class="col-md-6">
                <h3>
                    <img src="{% static 'img/destination/orang.png' %}" style="width: 10px">
                    <a name="{{ pro.name }}" style="color: black">{{ pro.title }}</a>
                    <a href="{% url 'messageApp:getDoc' pro.id %}"
                       style="font-size: 13px;float: right;padding-top: 10px">下载<b>{{ pro.title }}</b></a>
                </h3>
                <textarea rows="2" cols="20" style="width: 100%;height: 500px">
                    {{ pro.content }}
                </textarea>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

messageApp/templates/message.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block title %}
欢迎留言
{% endblock %}

{% block content %}
    <link href="{% static 'css/contact.css' %}" rel="stylesheet">
    <div class="container-fluid">
        <div class="row">
            <img class="img-responsive model-img"
                 src="{% static 'img/destination/special/spots2.jpg' %}"
                 style="width: 100%;">
        </div>
    </div>
    <!-- 主体内容 -->
    <div class="container">
        <div class="row row-3">
            <!-- 侧边导航栏 -->
            <div class="col-md-3">
                <div class="model-title">
                    留言板
                </div>
                <div class="model-list">
                    <ul class="list-group">
                        <li class="list-group-item" id="contact">
                            <a href="{% url 'messageApp:message' %}">欢迎留言</a>
                        </li>
                        <li class="list-group-item" id="recruit">
                            <a href="{% url 'messageApp:showreply' %}">留言回复</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- 留言板面 -->
            <div class="col-md-9">
                <div class="model-details-title">
                    欢迎留言
                </div>
                <div class="model-details">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        请填写您的留言
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <form action="." name="messageForm" method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
                                {% csrf_token %}  <!--规避跨站请求，不加，后台无法接受数据-->
                                <!-- 左侧 -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">姓名：</label>
                                        <div class="col-sm-9">
                                            {{messageForm.name|add_class:"form-control"|attr:"placeholder=请填写姓名"}}<!--模板表单变量-->
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">电话号码：</label>
                                        <div class="col-sm-9">
                                            {{messageForm.phone|add_class:"form-control"|attr:"placeholder=请填写电话号码"}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">邮箱：</label>
                                        <div class="col-sm-9">
                                            {{messageForm.email|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">留言标题：</label>
                                        <div class="col-sm-9">
                                            {{messageForm.title|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">留言内容：</label>
                                        <div class="col-sm-9">
                                            {{messageForm.content|add_class:"form-control"}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <center><input type="submit" class="btn btn-primary" value="提交" /></center>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

messageApp/templates/showreply.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}
欢迎留言
{% endblock %}

{% block content %}
    <link href="{% static 'css/contact.css' %}" rel="stylesheet">
{#    <div class="container-fluid">#}
{#        <div class="row">#}
{#            <img class="img-responsive model-img" src="{% static 'img/contact.jpg' %}">#}
{#        </div>#}
{#    </div>#}
    <!-- 主体内容 -->
    <div class="container">
        <div class="row row-3">
            <!-- 侧边导航栏 -->
            <div class="col-md-3">
                <div class="model-title">
                    留言板
                </div>
                <div class="model-list">
                    <ul class="list-group">
                        <li class="list-group-item" id="contact">
                            <a href="{% url 'messageApp:message' %}">欢迎留言</a>
                        </li>
                        <li class="list-group-item" id="recruit">
                            <a href="{% url 'messageApp:showreply' %}">留言回复</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- 留言板面 -->
            <div class="col-md-9">
                <div class="model-details-title">
                    留言回复
                </div>
                <div class="model-details">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        请查看留言回复
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <table border="1" style="width: 90%; margin-left: 5%; height: auto">
                                <tr style="font-weight: bolder">
                                    <td>姓名</td>
                                    <td>标题</td>
                                    <td>内容</td>
                                    <td>回复</td>
                                    <td>回复时间</td>
                                </tr>
                                {% for rep in replyList %}
                                    <tr>
                                        <td> {{rep.name|slice:"1"}}**</td>
                                        <td> {{rep.title}}  </td>
                                        <td> {{rep.content}} </td>
                                        <td> {{rep.replycontent}}</td>
                                        <td> {{rep.replyDate}} </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

messageApp/templates/successm.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
欢迎留言
{% endblock %}

{% block content %}
<!-- 主体内容 -->
<div class="container">
    <div class="row">
        <div class="alert alert-success">
            <strong>您已留言成功!</strong> 管理员将会尽快以邮件的形式回复您的留言，请耐心等待，谢谢！
        </div>
    </div>
</div>
{% endblock %}