TourKProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from homeApp.views import home
from django.conf import settings
from django.conf.urls.static import static
import xadmin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('destinationApp/', include('destinationApp.urls')),
    path('ticketApp/', include('ticketApp.urls')),
    path('hotelApp/', include('hotelApp.urls')),
    path('search/', include('haystack.urls')),
    path('noteApp/', include('noteApp.urls')),
    path('communtityApp/', include('communityApp.urls')),
    path('messageApp/', include('messageApp.urls')),
    path('', home, name='home'),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('xadmin/', xadmin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

hotelApp/urls.py
from django.urls import path
from . import views

app_name = 'hotelApp'

urlpatterns = [
    path('hotels/', views.hotels, name='hotels'),
    path('hotelDetail/<int:id>/<str:photoType>', views.hotelDetail, name='hotelDetail')
]

noteApp/urls.py
from django.urls import path
from . import views

app_name = 'noteApp'

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('route', views.routes, name='routes'),
    path('noteDetail/<int:id>/', views.noteDetail, name='noteDetail'),

]

ticketApp/urls.py
from django.urls import path
from . import views

app_name = 'ticketApp'

urlpatterns = [
    path('ticket/', views.ticket, name='ticket'),
    path('ticketDetail/', views.ticketDetail, name='ticketDetail'),
    # path('ticketType/<str:ticketType>/', views.ticketType, name='ticketType'),
    path('ticketOff/<str:ticketType>/<str:off>/<str:land>', views.ticketOff, name='ticketOff'),
    path('ticketSelf/', views.ticketSelf, name="ticketSelf"),
    path('search/', views.search, name='search'),
]

ticketApp/models.py
from django.db import models
import django.utils.timezone as timezone
class Ticket(models.Model):
    TICKET_CHOICES = (
        ('中国-韩国', '中国-韩国'),
        ('韩国-中国', '韩国-中国'),
    )
    AIRPORTLINES_CHOICES = (
        ('大韩航空', '大韩航空'), ('韩亚航空', '韩亚航空'), ('山东航空', '山东航空'),
        ('青岛航空', '青岛航空'), ('春秋航空', '春秋航空'), ('釜山航空', '釜山航空'),
        ('中国南方航空', '中国南方航空'), ('真航空', '韩亚航空'), ('中国国际航空', '中国国际航空'),
        ('中国东方航空', '中国东方航空'), ('济州航空', '济州航空'),
    )
    SIZE_CHOICES = (
        ('大型机', '大型机'),
        ('中型机', '中型机'),
        ('小型机', '小型机'),
    )
    CHANGE_CHOICES = (
        ('可退改签', '可退改签'),
        ('不可退改签', '不可退改签'),
    )
    FOOD_CHOICES = (
        ('有餐食', '有餐食'),
        ('不提供餐食', '不提供餐食'),
    )
    SITE_CHOICES = (
        ('经济舱', '经济舱'),
        ('商务舱', '商务舱'),
        ('头等舱', '头等舱'),
    )
    ticketType = models.CharField(choices=TICKET_CHOICES, max_length=10, verbose_name='飞机航向')
    airportType = models.CharField(choices=AIRPORTLINES_CHOICES, max_length=10, verbose_name='航空公司')
    logo = models.ImageField(upload_to='Airport/', blank=True, verbose_name="航空公司标志")
    number = models.CharField(max_length=10, verbose_name="航班号")
    sizeType = models.CharField(choices=SIZE_CHOICES, max_length=20, verbose_name='机体类型')
    off = models.CharField(max_length=50, verbose_name="起飞城市")
    offAirport = models.CharField(max_length=50, verbose_name="起飞机场")
    offTime = models.DateTimeField(max_length=20, default=timezone.now, verbose_name='起飞时间')
    middlePlace = models.CharField(max_length=10, blank=True, null=True, verbose_name="中转城市")
    middleTime = models.CharField(max_length=20, blank=True, null=True, verbose_name="中转时间")
    land = models.CharField(max_length=50, verbose_name="降落城市")
    landAirport = models.CharField(max_length=50, verbose_name="降落机场")
    landTime = models.DateTimeField(max_length=20, default=timezone.now, verbose_name='降落时间')
    flyTime = models.CharField(max_length=50, verbose_name="飞行时间")
    siteType = models.CharField(choices=SITE_CHOICES, max_length=5, verbose_name='座位等级')
    changeType = models.CharField(choices=CHANGE_CHOICES, max_length=10, verbose_name='退改签')
    foodType = models.CharField(choices=FOOD_CHOICES, max_length=10, verbose_name='餐食提供')
    luggageWeight = models.CharField(max_length=30, verbose_name="行李额")
    price = models.IntegerField(blank=True, null=True, verbose_name='机票价格')

    def __str__(self):
        return self.number

    class Meta:
        verbose_name = '航班'
        verbose_name_plural = '航班'
        ordering = ('-offTime', )

class selfService(models.Model):
    AIRPORTLINES_CHOICES = (
        ('大韩航空', '大韩航空'), ('韩亚航空', '韩亚航空'), ('山东航空', '山东航空'),
        ('青岛航空', '青岛航空'), ('春秋航空', '春秋航空'), ('釜山航空', '釜山航空'),
        ('中国南方航空', '中国南方航空'), ('真航空', '真航空'), ('中国国际航空', '中国国际航空'),
        ('中国东方航空', '中国东方航空'), ('济州航空', '济州航空'),
    )
    Name = models.CharField(choices=AIRPORTLINES_CHOICES, max_length=10, verbose_name='航空公司')
    Code = models.CharField(max_length=5, blank=True, null=True, verbose_name='航空公司代号')
    Time = models.CharField(max_length=50, blank=True, null=True, verbose_name='自助值机时间')
    Home = models.CharField(max_length=100, blank=True, null=True, verbose_name='航空公司官网')
    Logo = models.ImageField(upload_to='Airport/', blank=True, verbose_name="航空公司标志")

    class Meta:
        verbose_name = '航空公司信息'
        verbose_name_plural = '航空公司信息'

ticketApp/views.py
from django.db.models import Q
from django.shortcuts import render
from django.shortcuts import HttpResponse
from .models import Ticket
from .models import selfService
from pyquery import PyQuery as pq
import xlwt
from io import BytesIO
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from hotelApp.models import Hotel

def ticket(request):
    tickets = Ticket.objects.all().order_by('offTime', 'off', 'price')[:12]

    return render(
        request, 'ticketList.html', {
            'active_menu': 'ticket',
            'tickets': tickets,
        }
    )

def ticketDetail(request):

    ticketsList = Ticket.objects.all().order_by('offTime', 'off')

    return render(
        request, 'ticketDetail.html', {
            'active_menu': 'ticket',
            'ticketsList': ticketsList,
        }
    )

def ticketOff(request, ticketType, off, land):
    if ticketType == '全部':
        ticketsList = Ticket.objects.all().order_by('offTime', 'off')
        offList = ''
        landList = ''
        type_menu = 'type全部'
        ht = '韩国'
        hotelList = Hotel.objects.all().order_by('-score')[:4]

    elif ticketType == '韩国-中国':
        ticketsList = Ticket.objects.all().filter(ticketType=ticketType).order_by('offTime', 'off')
        List = Ticket.objects.filter(ticketType=ticketType)
        offList = List.values('off').distinct().order_by('off')
        landList = List.values('land').distinct().order_by('land')
        type_menu = ticketType
        ht = off
        hotelList = Hotel.objects.all().filter(city=off).order_by('-score')[:4]

    else:
        ticketsList = Ticket.objects.all().filter(ticketType=ticketType).order_by('offTime', 'off')
        List = Ticket.objects.filter(ticketType=ticketType)
        offList = List.values('off').distinct().order_by('off')
        landList = List.values('land').distinct().order_by('land')
        type_menu = ticketType
        ht = land
        hotelList = Hotel.objects.all().filter(city=land).order_by('-score')[:4]

    if off == "全部":
        ticketsList = ticketsList
        off_menu = 'off全部'
    else:
        ticketsList = ticketsList.all().filter(off=off).order_by('offTime')
        off_menu = off

    if land == "全部":
        ticketsList = ticketsList
        land_menu = 'land全部'
    else:
        ticketsList = ticketsList.all().filter(land=land).order_by('offTime')
        land_menu = land

    return render(
        request, 'ticketDetail.html', {
            'active_menu': 'ticket',
            'ticketsList': ticketsList,
            'ticketType': ticketType,
            'offList': offList,
            'landList': landList,
            'off': off,
            'land': land,
            'ht': ht,
            'type_menu': type_menu,
            'off_menu': off_menu,
            'land_menu': land_menu,
            'hotelList': hotelList,
        }
    )

def ticketSelf(request):

    selfList = selfService.objects.all().order_by('Name')

    return render(request, 'selfService.html', {
        'active_menu': 'ticket',
        'selfList': selfList,
    })

# def ticketImgs(request):
#
#     ImgsList = Ticket.objects.all().order_by('offTime', 'off')
#
#     return render(
#         request, 'ticketDetail.html', {
#             'active_menu': 'ticket',
#             'ImgsList': ImgsList,
#         }
#     )

def search(request):
    offkey = request.GET.get('offkey')
    landkey = request.GET.get('landkey')
    # offTimekey = request.GET.get('offTimekey')
    ticketsList = Ticket.objects.filter(off__icontains=offkey)\
        .filter(land__icontains=landkey)\
        # .filter(offTime__icontains=offTimekey)
    ticketName = "关于" + "\"" + offkey + "到" + landkey + "\"" + "的搜索结果"
    return render(request, 'searchTickets.html', {
        'active_menu': 'ticket',
        'ticketName': ticketName,
        'ticketsList': ticketsList,
    })

ticketApp/templates/searchTickets.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}机票|机票搜索{% endblock %}

{% block content %}
    <link href="{% static 'css/news.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/codemirror.js' %}"></script>
    <script src="{% static 'js/python.js' %}"></script>
    <style type="text/css">
        .CodeMirror {
            border-top: 1px solid black;
            border-bottom: 1px solid black;
        }
    </style>

    <div class="container">
        <div class="col-md-10" align="center" style="background-color: #EEE9E9;margin: 30px 0">
            <div style="padding-top: 20px">
                <b style="color: #777777;font-size: larger">请输入关键词进行搜索</b>
            </div>
            <div class="hidden-xs model-details-title-search" align="center" style="width: auto;float: none">
                <form method="get" id="searchform" action="{% url 'ticketApp:search' %}">
                    {% csrf_token %}
                    <div class="input-group col-md-12" style="width: 80%;padding: 50px">
                        <div class="col-md-9">
                            <input type="text" name="offkey" class="form-control" style="margin-bottom: 5px"
                                   placeholder="出发城市：例如 深圳/青岛/北京" required />
                            <input type="text" name="landkey" class="form-control" style="margin-top: 5px"
                                   placeholder="到达城市：例如 首尔/釜山/济州岛" required />
                        </div>
                        <div class="col-md-3">
                            <div class="input-group-btn">
                                <input type="submit" class="btn btn-default"
                                       style="width: 100%;height: 75px" value="🔍查询" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-2" style="float: right" align="right">
            <div class="col-md-12">
                <a href="{% url 'ticketApp:ticketSelf' %}">
                    <input type="button" value="自助值机" align="center"
                           style="font-size: 20px;background-color: #f7e1b5;color: #F4A460;border: none;
                           width: 150px;height: 130px;margin-top: 30px">
                </a>
            </div>
            <div class="col-md-12">
                <a href="http://www.weather.com.cn/forecast/world.shtml">
                    <input type="button" value="天气预报" align="center"
                       style="font-size: 20px;background-color: #f7e1b5;color: #F4A460;border: none;
                       width: 150px;height: 130px;margin-top: 15px">
                </a>
            </div>
        </div>
        <div class="model-details-title col-md-10" style="padding-top: 0;margin-top: 0">
            {{ ticketName }}<a style="font-size: 12px;float: right" href="{% url 'ticketApp:ticketOff' '全部' '全部' '全部' %}">更多其他机票>></a>
        </div>
        {% for tic in ticketsList %}
        <div class="row col-md-10">
            <div class="thumbnail" style="height: 100px;width: 103%">
                <div class="col-md-3">
                    <div class="col-md-4">
                            <img align="center" src="{{ tic.logo.url }}" style="width: 40px;padding-top: 20px">
                    </div>
                    <div class="col-md-8">
                        <p style="font-size: 10px;margin-top: 20px;float: left">{{ tic.airportType }}</p>
                        <p style="font-size: 10px;float: left;color: #777777">{{ tic.sizeType }} {{ tic.number }}</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="col-md-4">
                        <p align="left" style="font-size: 10px;margin-bottom: 0;color: #777777">{{ tic.landTime|date:"m-d" }}</p>
                        <h2 align="center" style="margin-top: 0">{{ tic.offTime|date:"H:i" }}</h2>
                        <p align="center" style="font-size: 12px">{{ tic.offAirport }}</p>
                    </div>
                    <div class="col-md-4">
                        <p align="center" style="color: #3c3c3c;margin-top: 20px;height: 0;font-size: 12px">{{ tic.flyTime }}</p>
                        <hr align="center" style="width: 90px;margin-top: 25px;margin-bottom: 0;size: 5px;color: #777777;">
                        {% if tic.middlePlace %}
                            <p align="center" style="color: #777778;font-size: 12px;margin-top: 2px;margin-bottom: 0">中转</p>
                            <p align="center" style="color: #777778;font-size: 12px;margin-top: 0;">{{ tic.middlePlace }}({{ tic.middleTime }})</p>
                        {% endif %}
                    </div>
                    <div class="col-md-4">
                        <p align="left" style="font-size: 10px;margin-bottom: 0;color: #777777">{{ tic.landTime|date:"m-d" }}</p>
                        <h2 align="center" style="margin-top: 0">{{ tic.landTime|date:"H:i" }}</h2>
                        <p align="center" style="font-size: 12px">{{ tic.landAirport }}</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="col-md-6">
                        <h3 align="center" style="float: right;color: #F4A460;margin-top: 30px;height: 15px">¥{{ tic.price }}</h3>
                        <p style="font-size: 12px;color: #777777;float: right;margin-bottom: 20px">{{ tic.siteType }}</p>
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#{{ tic.number }}"
                                style="background-color: #F4A460;color: white;float: left;
                               height: 40px;width: 95px;border: none;margin-top: 25px;font-size: 15px">
                            查看详情
                        </button>
                        <div class="modal fade" id="{{ tic.number }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                            &times;
                                        </button>
                                        <h4 class="modal-title" id="myModalLabel">
                                            <b style="font-size: 15px">航班</b><i style="color: #F4A460;font-style: normal">{{ tic.number }}</i><b style="font-size: 15px">详情</b>
                                        </h4>
                                    </div>
                                    <div class="modal-body col-md-12">
                                        <div class="col-md-1"></div>
                                        <div class="col-md-5" style="padding-top: 20px">
                                            <p><b>飞行时间：</b>{{ tic.flyTime }}</p>
                                            <p><b>座位等级：</b>{{ tic.siteType }}</p>
                                            <p><b>退改签：</b>{{ tic.changeType }}</p>
                                            <p><b>餐食提供：</b>{{ tic.foodType }}</p>
                                            <p><b>餐食提供：</b>{{ tic.luggageWeight }}</p>
                                            <p><b>价格：</b><span style="color: #F4A460;font-size: 20px">¥{{ tic.price }}</span></p>
                                        </div>
                                        <div class="col-md-5">
                                            <img src="{{ tic.logo.url }}" style="width: 100%;padding: 20px">
                                        </div>
                                        <div class="col-md-1"></div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                    </div>
                                </div><!-- /.modal-content -->
                            </div><!-- /.modal -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
            <div class="col-md-10">
                <h4 style="color: #777777;" align="center">暂时没有这类航班信息哦~</h4>
            </div>
        {% endfor %}
    </div>
{% endblock %}

ticketApp/templates/ticketDetail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}机票|机票详情{% endblock %}

{% block content %}
    <link href="{% static 'css/news.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/codemirror.js' %}"></script>
    <script src="{% static 'js/python.js' %}"></script>
    <style type="text/css">
        .CodeMirror {
            border-top: 1px solid black;
            border-bottom: 1px solid black;
        }
    </style>

    <div class="container">
        <div class="col-md-10" style="margin-bottom: 5px;padding-left: 0">
            <h3>请根据以下条件筛选航班：<i style="color: #777777;font-style: normal;font-size: 15px">{{ off }}---->{{ land }}</i></h3>
            <ul class="nav navbar-nav" style="width: 100%;height: 40px;margin-top: 0">
                <li class="nav-top" >
                    <p align="center" style="font-size: 15px;font-weight: bolder;margin-top: 14px">航班航向</p>
                </li>
                <li class="nav-top active" style="width: 100px" id="type全部">
                    <a href="{% url 'ticketApp:ticketOff' '全部' '全部' '全部' %}" style="font-size: 15px;color: #F4A460">全部</a>
                </li>
                <li class="nav-top" style="width: 100px" id="中国-韩国">
                    <a href="{% url 'ticketApp:ticketOff' '中国-韩国' '全部' '全部' %}" style="font-size: 15px;color: #F4A460">中国-韩国</a>
                </li>
                <li class="nav-top" style="width: 100px" id="韩国-中国">
                    <a href="{% url 'ticketApp:ticketOff' '韩国-中国' '全部' '全部' %}" style="font-size: 15px;color: #F4A460">韩国-中国</a>
                </li>
            </ul>
            <ul class="nav navbar-nav" style="width: 100%;height: auto;margin-top: 5px">
                <li class="nav-top">
                    <p align="center" style="font-size: 15px;font-weight: bolder;margin-top: 14px">出发城市</p>
                </li>
                <li class="nav-top" style="width: 100px" id="off全部">
                    <a href="{% url 'ticketApp:ticketOff' ticketType '全部' land %}"
                       style="font-size: 15px;color: #F4A460;padding: 15px 0;
                               width: 100px">全部</a>
                </li>
                {% for tic in offList %}
                    <li class="nav-top" style="width: 100px" id="{{ tic.off }}">
                        <a href="{% url 'ticketApp:ticketOff' ticketType tic.off land %}"
                           style="font-size: 15px;color: #F4A460;padding: 15px 0;
                              width: 100px">{{ tic.off }}</a>
                    </li>
                {% endfor %}
            </ul>
            <ul class="nav navbar-nav" style="width: 100%;height: auto;margin-top: 0">
                <li class="nav-top">
                    <p align="center" style="font-size: 15px;font-weight: bolder;margin-top: 14px">到达城市</p>
                </li>
                <li class="nav-top" style="width: 100px" id="land全部">
                    <a href="{% url 'ticketApp:ticketOff' ticketType off '全部' %}" style="font-size: 15px;color: #F4A460;padding: 15px 0;
                               width: 100px">全部</a>
                </li>
                {% for tic in landList %}
                    <li class="nav-top" style="width: 100px" id="{{ tic.land }}">
                            <a href="{% url 'ticketApp:ticketOff' ticketType off tic.land %}" style="font-size: 15px;color: #F4A460;padding: 15px 0;
                               width: 100px">{{ tic.land }}
                            </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-2" style="float: right" align="right">
            <div class="col-md-12">
                <a href="{% url 'ticketApp:ticketSelf' %}">
                    <input type="button" value="自助值机" align="center"
                           style="font-size: 20px;background-color: #f7e1b5;color: #F4A460;border: none;
                           width: 150px;height: 130px;margin-top: 30px">
                </a>
            </div>
            <div class="col-md-12">
                <a href="http://www.weather.com.cn/forecast/world.shtml">
                    <input type="button" value="天气预报" align="center"
                       style="font-size: 20px;background-color: #f7e1b5;color: #F4A460;border: none;
                       width: 150px;height: 130px;margin-top: 15px">
                </a>
            </div>
            <div class="col-md-12" style="margin: 30px 0">
                <b style="float: left">{{ ht }}酒店推荐</b>
            </div>
            {% for sp in hotelList %}
                <div class="col-md-12">
                    {% for img in sp.hotelImgs.all %}
                        {% if forloop.first %}
                            <a href="{% url 'hotelApp:hotelDetail' sp.id '全部' %}">
                                <img src="{{ img.photo.url }}"
                                     style="width: 115%;margin-bottom: 20px;height: 100px;">
                            </a>
                        {% endif %}
                    {% endfor %}
                    <div class="carousel-caption nav-title" style="padding-bottom: 5px" align="center">
                        <i style="padding-bottom: 0;font-size: 12px;font-style: normal">
                            {{ sp.title }}
                        </i>
                    </div>
                </div>
                {% empty %}
                <p align="center" style="width: 90%">暂时没有该信息哦！</p>
            {% endfor %}
        </div>
        <div class="model-details-title col-md-10" style="padding-top: 0;margin-top: 0">

        </div>
        {% for tic in ticketsList %}
        <div class="row col-md-10">
            <div class="thumbnail" style="height: 100px;width: 103%">
                <div class="col-md-3">
                    <div class="col-md-4">
                            <img align="center" src="{{ tic.logo.url }}" style="width: 40px;padding-top: 20px">
                    </div>
                    <div class="col-md-8">
                        <p style="font-size: 10px;margin-top: 20px;float: left">{{ tic.airportType }}</p>
                        <p style="font-size: 10px;float: left;color: #777777">{{ tic.sizeType }} {{ tic.number }}</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="col-md-4">
                        <p align="left" style="font-size: 10px;margin-bottom: 0;color: #777777">{{ tic.landTime|date:"m-d" }}</p>
                        <h2 align="center" style="margin-top: 0">{{ tic.offTime|date:"H:i" }}</h2>
                        <p align="center" style="font-size: 12px">{{ tic.offAirport }}</p>
                    </div>
                    <div class="col-md-4">
                        <p align="center" style="color: #3c3c3c;margin-top: 20px;height: 0;font-size: 12px">{{ tic.flyTime }}</p>
                        <hr align="center" style="width: 90px;margin-top: 25px;margin-bottom: 0;size: 5px;color: #777777;">
                        {% if tic.middlePlace %}
                            <p align="center" style="color: #777778;font-size: 12px;margin-top: 2px;margin-bottom: 0">中转</p>
                            <p align="center" style="color: #777778;font-size: 12px;margin-top: 0;">{{ tic.middlePlace }}({{ tic.middleTime }})</p>
                        {% endif %}
                    </div>
                    <div class="col-md-4">
                        <p align="left" style="font-size: 10px;margin-bottom: 0;color: #777777">{{ tic.landTime|date:"m-d" }}</p>
                        <h2 align="center" style="margin-top: 0">{{ tic.landTime|date:"H:i" }}</h2>
                        <p align="center" style="font-size: 12px">{{ tic.landAirport }}</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="col-md-6">
                        <h3 align="center" style="float: right;color: #F4A460;margin-top: 30px;height: 15px">¥{{ tic.price }}</h3>
                        <p style="font-size: 12px;color: #777777;float: right;margin-bottom: 20px">{{ tic.siteType }}</p>
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#{{ tic.number }}"
                                style="background-color: #F4A460;color: white;float: left;
                               height: 40px;width: 95px;border: none;margin-top: 25px;font-size: 15px">
                            查看详情
                        </button>
                        <div class="modal fade" id="{{ tic.number }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                            &times;
                                        </button>
                                        <h4 class="modal-title" id="myModalLabel">
                                            <b style="font-size: 15px">航班</b><i style="color: #F4A460;font-style: normal">{{ tic.number }}</i><b style="font-size: 15px">详情</b>
                                        </h4>
                                    </div>
                                    <div class="modal-body col-md-12">
                                        <div class="col-md-1"></div>
                                        <div class="col-md-5" style="padding-top: 20px">
                                            <p><b>飞行时间：</b>{{ tic.flyTime }}</p>
                                            <p><b>座位等级：</b>{{ tic.siteType }}</p>
                                            <p><b>退改签：</b>{{ tic.changeType }}</p>
                                            <p><b>餐食提供：</b>{{ tic.foodType }}</p>
                                            <p><b>餐食提供：</b>{{ tic.luggageWeight }}</p>
                                            <p><b>价格：</b><span style="color: #F4A460;font-size: 20px">¥{{ tic.price }}</span></p>
                                        </div>
                                        <div class="col-md-5">
                                            <img src="{{ tic.logo.url }}" style="width: 100%;padding: 20px">
                                        </div>
                                        <div class="col-md-1"></div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                    </div>
                                </div><!-- /.modal-content -->
                            </div><!-- /.modal -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
            <h4 style="color: #777777;" align="center">暂时没有这类航班信息哦~</h4>
        {% endfor %}
    </div>

    </script>
{% endblock %}